import React, { useEffect, useState } from "react";

import { readApiResponse } from "../../api/client.js";
import {
  formatCycleDuration,
  formatDuration,
  formatValue,
  poConversionText,
  poInventoryUnitCost,
  toNumber,
} from "../../domain/formatting.js";
import { Badge, Button, Stat } from "../../components/ui.jsx";

export function POExplorer({ target, onClose, onApply }) {
  const [rows, setRows] = useState([]), [selected, setSelected] = useState(null), [error, setError] = useState("");
  useEffect(() => { if (!target) return; (async () => { try { setError(""); const params = target.kind === "material" ? "part_id=" + encodeURIComponent(target.row.ucmMaterialID || "") : "part_id=" + encodeURIComponent(target.partId || "") + "&method_operation_id=" + encodeURIComponent(target.row.ucoPartOperationLineID || target.row.ucoOperationID || ""); const payload = await readApiResponse(await fetch("/api/purchase-orders/" + (target.kind === "material" ? "material" : "external-operation") + "?" + params)); setRows(payload.purchase_orders || payload.rows || []); } catch (err) { setError(err.message); } })(); }, [target]);
  if (!target) return null;
  return <div className="modal-backdrop"><section className="po-modal"><header><div><span className="eyebrow">Purchase orders</span><h2>{target.kind === "material" ? target.row.ucmMaterialID : target.row.ucoOperationDescription}</h2></div><Button tone="secondary" onClick={onClose}>Close</Button></header>{error && <div className="error-box">{error}</div>}<div className="po-panes"><div className="po-list">{rows.length ? rows.map((row, index) => <button type="button" key={index} className={selected === row ? "selected" : ""} onClick={() => setSelected(row)} onDoubleClick={() => onApply(row)}><strong>{row.pmlPurchaseOrderID || row.po_id || "-"}</strong><span>{formatValue("ucmLastPOCost", target.kind === "material" ? poInventoryUnitCost(row) : row.pmlPurchaseUnitCostBase ?? row.pmlExtendedCostBase ?? row.unit_cost)}</span>{target.kind === "material" && poConversionText(row) && <span>{poConversionText(row)}</span>}<span>{row.pmlDueDate || row.pmlCreatedDate || row.date || ""}</span></button>) : <p>No matching purchase order lines.</p>}</div><div className="po-details"><h3>{target.kind === "material" ? "Unit conversion" : "SQL row details"}</h3>{selected ? <>{target.kind === "material" && <div className="stat-grid compact"><Stat label="Purchase unit" field="ucmLastPOCost" value={selected.pmlPurchaseUnitCostBase} /><Stat label="Conversion" value={selected.pmlConversionFactor || 1} /><Stat label="Inventory unit" field="ucmLastPOCost" value={poInventoryUnitCost(selected)} /></div>}<pre>{JSON.stringify(selected, null, 2)}</pre></> : <p>Select a purchase order line.</p>}</div></div></section></div>;
}

export function JobExplorer({ target, onClose, onCostQuantity }) {
  const [rows, setRows] = useState([]), [selected, setSelected] = useState(null), [error, setError] = useState("");
  const isOperation = target?.kind === "operation";
  const partId = target?.partId || target?.row?.ucmMaterialID || "";
  const revisionId = target?.revisionId || "";
  const title = target?.title || partId;
  const operationSequence = target?.operationSequence || target?.row?.ucoPartOperationLineID || "";
  useEffect(() => { if (!target) return; (async () => { try { setError(""); const url = isOperation ? "/api/jobs/operation?part_id=" + encodeURIComponent(partId) + "&revision_id=" + encodeURIComponent(revisionId) + "&operation_sequence=" + encodeURIComponent(operationSequence) : "/api/jobs/recent?part_id=" + encodeURIComponent(partId) + "&revision_id=" + encodeURIComponent(revisionId); const payload = await readApiResponse(await fetch(url)); const jobs = payload.jobs || []; setRows(jobs); setSelected(jobs[0] || null); } catch (err) { setError(err.message); setRows([]); setSelected(null); } })(); }, [target, isOperation, partId, revisionId, operationSequence]);
  if (!target) return null;
  return <div className="modal-backdrop"><section className="history-modal"><header><div><span className="eyebrow">{isOperation ? "Operation jobs" : "Recent jobs"}</span><h2>{title}</h2></div><Button tone="secondary" onClick={onClose}>Close</Button></header>{error && <div className="error-box">{error}</div>}<div className="history-body"><div className="history-list job-list">{rows.map((row) => <button type="button" key={row.jmpJobID + "." + (row.jmoJobOperationID || "")} className={selected?.jmpJobID === row.jmpJobID ? "selected" : ""} onClick={() => setSelected(row)} onDoubleClick={() => onCostQuantity(row)}><strong>{row.jmpJobID}</strong>{isOperation ? <><span>{formatCycleDuration(row.suggested_cycle_time_hours)} / part</span><span>Qty {formatValue("ucpCostQuantity", row.operation_quantity)}</span><Badge tone={toNumber(row.jmoActualProductionHours) > 0 ? "green" : "amber"}>{toNumber(row.jmoActualProductionHours) > 0 ? "Actual" : "No runtime"}</Badge></> : <><span>Qty {formatValue("ucpCostQuantity", row.job_quantity)}</span><span>{row.jmpClosedDate || row.jmpCreatedDate || ""}</span><Badge>{row.jmpQuantityCompleted ? "Completed" : "Planned"}</Badge></>}</button>)}</div><div className="history-detail">{selected ? <>{isOperation ? <div className="stat-grid compact"><Stat label="Cycle" value={formatCycleDuration(selected.suggested_cycle_time_hours)} /><Stat label="Setup" value={formatDuration(selected.suggested_setup_time_hours)} /><Stat label="Operation quantity" field="ucpCostQuantity" value={selected.operation_quantity} /><Stat label="Actual runtime" value={formatDuration(selected.jmoActualProductionHours)} /><Stat label="Work center" value={selected.jmoWorkCenterID || "-"} /><Stat label="Process" value={selected.jmoProcessID || "-"} /></div> : <div className="stat-grid compact"><Stat label="Job quantity" field="ucpCostQuantity" value={selected.job_quantity} /><Stat label="Made" field="ucpCostQuantity" value={selected.jmpQuantityCompleted} /><Stat label="Planned" field="ucpCostQuantity" value={selected.jmpProductionQuantity} /><Stat label="Date" value={selected.jmpClosedDate || selected.jmpCreatedDate || "-"} /></div>}<div className="history-actions"><Button onClick={() => onCostQuantity(selected)}>{isOperation ? "Use timing" : target.kind === "part" ? "Use quantity" : "Cost this quantity"}</Button></div><pre>{JSON.stringify(selected, null, 2)}</pre></> : <p>{isOperation ? "No matching operation jobs found for this sequence." : "No recent jobs found for this part."}</p>}</div></div></section></div>;
}

export function CostHistoryModal({ target, onClose, onUseRun, onUseUnitCost, onCostQuantity, onNewRun, onSetCurrent }) {
  const rows = target?.rows || [];
  const [selected, setSelected] = useState(rows.find((row) => row.ucpIsCurrent) || rows[0] || null);
  useEffect(() => { setSelected(rows.find((row) => row.ucpIsCurrent) || rows[0] || null); }, [target]);
  if (!target) return null;
  const isMaterial = target.kind === "material";
  const title = isMaterial ? target.row.ucmMaterialID : target.partId;
  return <div className="modal-backdrop"><section className="history-modal"><header><div><span className="eyebrow">{isMaterial ? "Material cost history" : "Cost history"}</span><h2>{title}</h2></div><Button tone="secondary" onClick={onClose}>Close</Button></header>{target.message && <div className="error-box">{target.message}</div>}<div className="history-body"><div className="history-list">{rows.map((row) => <button type="button" key={row.ucpPartCostID} className={selected?.ucpPartCostID === row.ucpPartCostID ? "selected" : ""} onClick={() => setSelected(row)} onDoubleClick={() => isMaterial ? onUseUnitCost(row) : onUseRun(row)}><strong>{formatValue(isMaterial ? "ucpUnitRawCost" : "ucpUnitMarkedUpCost", isMaterial ? row.ucpUnitRawCost : row.ucpUnitMarkedUpCost)}</strong><span>Qty {formatValue("ucpCostQuantity", row.ucpCostQuantity)}</span><span>{row.ucpDateCosted || ""}</span>{row.ucpIsCurrent ? <Badge tone="green">Current</Badge> : <Badge>Saved</Badge>}</button>)}</div><div className="history-detail">{selected ? <><div className="stat-grid compact"><Stat label="Unit raw" field="ucpUnitRawCost" value={selected.ucpUnitRawCost} /><Stat label="Unit marked up" field="ucpUnitMarkedUpCost" value={selected.ucpUnitMarkedUpCost} /><Stat label="Quantity" field="ucpCostQuantity" value={selected.ucpCostQuantity} /><Stat label="Total" field="ucpTotalMarkedUpCost" value={selected.ucpTotalMarkedUpCost} /></div><div className="history-actions">{isMaterial ? <><Button onClick={() => onUseUnitCost(selected)}>Use raw cost</Button><Button tone="secondary" onClick={() => onCostQuantity(selected)}>Re-cost quantity</Button></> : <Button onClick={() => onUseRun(selected)}>Open as starting point</Button>}<Button tone="secondary" onClick={() => onSetCurrent(selected)}>Make current</Button><Button tone="secondary" onClick={onNewRun}>{isMaterial ? "Start new run" : "Use ERP defaults"}</Button></div>{selected.ucpNotes && <p>{selected.ucpNotes}</p>}</> : <><p>No saved costing runs.</p>{isMaterial && <div className="history-actions"><Button onClick={onNewRun}>Start new run</Button></div>}</>}</div></div></section></div>;
}


