import { moneyFields } from "./model.js";

export function toNumber(value) { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : 0; }
export function numberOr(value, fallback) { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : fallback; }

export function formatValue(key, value) { if (value === null || value === undefined || value === "") return "-"; if (key === "ucoExternalJob") return value ? "External" : "Internal"; if (moneyFields.has(key) && typeof value === "number") return value.toLocaleString(undefined, { style: "currency", currency: "USD" }); if (typeof value === "number") return value.toLocaleString(undefined, { maximumFractionDigits: 5 }); if (typeof value === "boolean") return value ? "Yes" : "No"; return String(value); }
export function poInventoryUnitCost(row) { return toNumber(row.pmlInventoryUnitCostBase ?? row.pmlPurchaseUnitCostBase ?? row.pmlExtendedCostBase ?? row.unit_cost); }
export function poPurchaseUnit(row) { return row.pmlPurchaseUnitOfMeasure || row.pmlPurchaseUnitOfMeasureID || row.pmlPurchaseUOM || row.pmlPurchaseUM || "purchase unit"; }
export function poInventoryUnit(row) { return row.pmlInventoryUnitOfMeasure || row.pmlInventoryUnitOfMeasureID || row.pmlInventoryUOM || row.pmlInventoryUM || "inventory unit"; }
export function poConversionText(row) { const factor = row.pmlConversionFactor; if (factor === null || factor === undefined || factor === "" || toNumber(factor) === 1) return ""; return formatValue("ucmLastPOCost", row.pmlPurchaseUnitCostBase) + "/" + poPurchaseUnit(row) + " x " + formatValue("pmlConversionFactor", factor) + " = " + formatValue("ucmLastPOCost", row.pmlInventoryUnitCostBase) + "/" + poInventoryUnit(row); }
export function materialConversionFactor(row) { return numberOr(row?.ucmLastPOConversionFactor, 1); }
export function materialPurchaseUnit(row) { return row?.ucmLastPOPurchaseUnit || row?.ucmPurchaseUnitOfMeasure || "purchase unit"; }
export function materialInventoryUnit(row) { return row?.ucmLastPOInventoryUnit || row?.ucmInventoryUnitOfMeasure || "inventory unit"; }
export function materialPurchaseUnitCost(row) { if (row?.ucmPurchaseUnitCost !== null && row?.ucmPurchaseUnitCost !== undefined) return toNumber(row.ucmPurchaseUnitCost); if (row?.ucmLastPOPurchaseUnitCost !== null && row?.ucmLastPOPurchaseUnitCost !== undefined) return toNumber(row.ucmLastPOPurchaseUnitCost); const factor = materialConversionFactor(row); return factor === 0 ? 0 : toNumber(row?.ucmUnitCost) / factor; }

export function parseTimeHours(value, fallback) { const text = String(value ?? "").trim(); if (!text) return fallback; if (text.includes(":")) { const [h, m] = text.split(":"); return toNumber(h) + toNumber((m || "0").slice(0, 2)) / 60; } const parsed = Number(text); return Number.isFinite(parsed) ? parsed : fallback; }
export function hoursToClock(hours) { const normalized = ((hours % 24) + 24) % 24; const h = Math.floor(normalized); const minutes = Math.round((normalized - h) * 60); return String((h + Math.floor(minutes / 60)) % 24).padStart(2, "0") + ":" + String(minutes % 60).padStart(2, "0"); }
export function parseDurationInput(value) { const text = String(value ?? "").trim().toLowerCase(); if (!text) return null; const colon = text.match(/^(\d+(?:\.\d+)?)(?::(\d+(?:\.\d+)?))?(?::(\d+(?:\.\d+)?))?$/); if (colon && text.includes(":")) return toNumber(colon[1]) + toNumber(colon[2]) / 60 + toNumber(colon[3]) / 3600; let total = 0, matched = false; const units = /(\d+(?:\.\d+)?)\s*(h|hr|hrs|hour|hours|m|min|mins|minute|minutes|s|sec|secs|second|seconds)/g; let match; while ((match = units.exec(text))) { matched = true; const unit = match[2][0]; total += unit === "h" ? toNumber(match[1]) : unit === "m" ? toNumber(match[1]) / 60 : toNumber(match[1]) / 3600; } if (matched) return total; const parsed = Number(text); return Number.isFinite(parsed) ? parsed : null; }
export function formatDurationInput(hours) { const total = Math.round(toNumber(hours) * 3600); if (!total) return "0m"; const h = Math.floor(total / 3600), m = Math.floor((total % 3600) / 60), s = total % 60; return [[h, "h"], [m, "m"], [s, "s"]].filter(([n]) => n).map(([n, u]) => n + u).join(" "); }
export function durationParts(hours) { const total = Math.max(0, Math.round(toNumber(hours) * 3600)); return { h: Math.floor(total / 3600), m: Math.floor((total % 3600) / 60), s: total % 60 }; }
export function formatDuration(hours) { const value = toNumber(hours); if (value < 1) return Math.round(value * 60) + " min"; if (value < 24) return value.toFixed(value >= 10 ? 1 : 2).replace(/\.0+$/, "") + " hr"; const days = Math.floor(value / 24); const rest = value - days * 24; return days + " day" + (days === 1 ? "" : "s") + (rest > 0.05 ? " " + formatDuration(rest) : ""); }
export function formatCycleDuration(hours) { const value = toNumber(hours); if (value <= 0) return "0s"; const total = Math.max(1, Math.round(value * 3600)); if (total < 60) return total + "s"; if (total < 3600) { const m = Math.floor(total / 60), s = total % 60; return s ? m + "m " + s + "s" : m + "m"; } return formatDuration(value); }
